repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^esologs/get_.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^esologs/get_.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^esologs/(get_.*\.py|input_types\.py|enums\.py|base_model\.py|exceptions\.py|async_base_client\.py)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports, --no-warn-return-any]
        exclude: ^(esologs/(get_.*\.py|input_types\.py|enums\.py|base_model\.py|exceptions\.py|async_base_client\.py)|tests/.*\.py|access_token\.py)$

  - repo: local
    hooks:
      - id: no-print-statements
        name: No print statements
        entry: bash -c 'if grep -r "print(" esologs/ tests/ --include="*.py"; then exit 1; fi'
        language: system
        pass_filenames: false
