# Read the Docs configuration file for ESO Logs Python
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, set of tools, and language to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changes in the docs directory or YAML file.
      # You can add any other files or directories that you'd like here as well,
      # like your docs requirements file, or other files that will change your docs build.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/v2/update-main-before-refactor HEAD -- docs/ .readthedocs.yml requirements.txt; then
          echo "No documentation changes found in PR, cancelling build."
          exit 183
        fi

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Formats to build
formats:
  - pdf
  - htmlzip
