site_name: ESO Logs Python
site_description: A comprehensive Python client library for the ESO Logs API v2
site_url: https://esologs-python.readthedocs.io/
repo_url: https://github.com/knowlen/esologs-python
repo_name: knowlen/esologs-python
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en

  # Vim-style color scheme - dark only
  palette:
    # Dark mode only (vim style)
    - scheme: slate
      primary: custom
      accent: custom

  # Typography - Regular font for UI, monospace for code
  font:
    text: Inter
    code: JetBrains Mono

  # Features
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress  # Show loading progress bar
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune  # Reduce DOM size for better performance
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.lazy  # Lazy load images and iframes

  # Icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  # Logo and favicon
  logo: assets/logo.png
  favicon: assets/logo.png

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Authentication: authentication.md
    - Quickstart: quickstart.md
  - API Reference:
    - Game Data: api-reference/game-data.md
    - Character Data: api-reference/character-data.md
    - Guild Data: api-reference/guild-data.md
    - World Data: api-reference/world-data.md
    - Report Analysis: api-reference/report-analysis.md
    - Report Search: api-reference/report-search.md
    - System Enspoints: api-reference/system.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Changelog: changelog.md

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # Emoji extension disabled due to YAML validation issues with Python tags
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  # Mermaid disabled due to YAML validation issues with Python tags
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      # Language setting for better tokenization
      lang: en

      # Custom separator for better code/API tokenization
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

      # Search pipeline for better results
      pipeline:
        - stemmer         # Reduces words to root form (searching/searches → search)
        - stopWordFilter  # Removes common words (the, is, at, which)
        - trimmer        # Removes whitespace

      # Prebuild index for faster initial load
      prebuild_index: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
        reduce_boolean_attributes: true
        remove_optional_attribute_quotes: false
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: false  # Reduce git operations

# Customization
extra_css:
  - stylesheets/vim-dark-theme.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/search-shortcuts.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Additional configuration
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/knowlen/esologs-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/esologs-python/
  # Analytics disabled - no cookies used
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX  # Set via environment variable GOOGLE_ANALYTICS_KEY
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           <a href="https://github.com/knowlen/esologs-python/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you found lacking</a>.
  generator: false

# Copyright
copyright: |
  &copy; 2024 esologs-python.
